# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['PreProcess', 'RecommenderStrategyFactory', 'NumericStrategy']

# Cell
from sklearn.preprocessing import MinMaxScaler
from scipy.spatial.distance import pdist, squareform
from pandas_profiling import ProfileReport

import pandas as pd
import numpy as np
import nltk

# Cell
class PreProcess:
    "Preprocess class to include all data preparation functions"
    def __init__(self, ctx):
        self.ctx = ctx

    def clean_duplicates(self):
        "Clean duplicates method"
        #TODO:
        #   CHECK FOR DUPLICATES BASED ON DESCRIPTION AND ATTRIBUTES
        # REMOVE THEM
        return 1

    def cols_munging(self, dataframe, fillna = True):
        "Columns preparation method"
        #Rename column
        df = dataframe.rename(columns={"Temperatura_Servicio":"temperatura"})
        #Create ID for beers
        df['beerID'] = (range(1, len(df) + 1))
        df = df.set_index(df['beerID'].astype(str))
        #Move beerID to first col
        cols = df.columns.tolist()
        cols.insert(0, cols.pop(cols.index('beerID')))
        df = df.reindex(columns= cols)

        #Convert to lowercase
        df = df.applymap(lambda s:s.lower() if type(s) == str else s)

        #Removes c from
        df['temperatura'] = df['temperatura'].replace('c', '')

        return df

    def fill_na(self, dataframe, method = 'median'):
        "Replaces NaN values with method"
        if method == '0':
            df = dataframe.fillna(0)

        if method == 'mean':
            df = dataframe.fillna(dataframe.mean())

        else:
            df = dataframe.fillna(dataframe.median())

        return df



    def scale_cols(self, dataframe):
        "Min Max scaler for numeric columns"
        #num_cols = dataframe.columns[dataframe.dtypes.apply(lambda c: np.issubdtype(c, np.number))]

        scaler = MinMaxScaler()
        #dataframe[num_cols] = scaler.fit_transform(dataframe[num_cols])
        df_scaled = pd.DataFrame(
            scaler.fit_transform(dataframe[self.ctx['numeric_cols']]),
                                 columns=dataframe[self.ctx['numeric_cols']].columns
            )

        return df_scaled

# Cell
class RecommenderStrategyFactory:
    "Strategy factory"
    def __init__(self, ctx):
        self.context = ctx

    def createStrategy(self, strategy):
        recommender_strategy = strategy.lower()

        if recommender_strategy == 'numeric':
            instance = NumericStrategy(self.context)

        else:
            instance = DescriptionAndNumeric(self.context)

        return instance

# Cell
class NumericStrategy:
    "Numeric based recommender system"
    def __init__(self, ctx):
        self.ctx = ctx

    def model_builder(self, dataframe):
        preprocessor = PreProcess(self.ctx)
        df = preprocessor.cols_munging(dataframe)
        df = preprocessor.fill_na(df, 'median')
        df = preprocessor.scale_cols(df)


        return df

    def exec_strategy(self, dataframe, distance = 'cosine'):
        if distance == 'euclidean':
             recommender_df = pd.DataFrame(
             squareform(pdist(dataframe[self.ctx['numeric_cols']])),
             columns = dataframe.index.astype(str),
             index = dataframe.index
             )

        else:
            recommender_df = pd.DataFrame(
            squareform(pdist(dataframe[self.ctx['numeric_cols']], metric = 'cosine')),
            columns = dataframe.index,
            index = dataframe.index
            )

        return recommender_df